"""Club tactical profiles and philosophies"""


CLUB_PROFILES = {
    "Manchester City": {
        "philosophy": "Possession-based attacking",
        "description": "Dominant possession, high pressing, intricate passing",
        "strengths": [
            "Ball progression and creative playmaking",
            "High-press defensive recovery",
            "Possession retention in midfield",
        ],
        "style_weights": {
            "possession": 0.25,
            "pressing": 0.20,
            "transitions": 0.15,
            "creativity": 0.20,
            "ball_progression": 0.15,
            "direct_play": 0.02,
            "defensive_work": 0.03,
        },
        "metric_preferences": {
            "goals_per_90": 0.10,
            "assists_per_90": 0.15,
            "progressive_carries": 0.20,
            "successful_dribbles": 0.12,
            "key_passes": 0.18,
            "xg": 0.12,
            "xa": 0.13,
        },
    },
    "Arsenal": {
        "philosophy": "High-press counter-attacking",
        "description": "Aggressive pressing, quick transitions, wide playmaking",
        "strengths": [
            "Wide attacking play and direct finishing",
            "Transition speed and exploitation",
            "High defensive pressure",
        ],
        "style_weights": {
            "possession": 0.15,
            "pressing": 0.25,
            "transitions": 0.20,
            "creativity": 0.15,
            "ball_progression": 0.10,
            "direct_play": 0.08,
            "defensive_work": 0.07,
        },
        "metric_preferences": {
            "goals_per_90": 0.15,
            "assists_per_90": 0.12,
            "progressive_carries": 0.15,
            "successful_dribbles": 0.15,
            "key_passes": 0.14,
            "xg": 0.15,
            "xa": 0.12,
        },
    },
    "Liverpool": {
        "philosophy": "Gegenpressing with intensity",
        "description": "Relentless pressing, box-to-box intensity, direct finishing",
        "strengths": [
            "Pressing and ball recovery",
            "Direct attacking transitions",
            "Midfielder work rate and box presence",
        ],
        "style_weights": {
            "possession": 0.12,
            "pressing": 0.28,
            "transitions": 0.22,
            "creativity": 0.12,
            "ball_progression": 0.10,
            "direct_play": 0.10,
            "defensive_work": 0.06,
        },
        "metric_preferences": {
            "goals_per_90": 0.16,
            "assists_per_90": 0.10,
            "progressive_carries": 0.12,
            "successful_dribbles": 0.10,
            "key_passes": 0.12,
            "xg": 0.16,
            "xa": 0.10,
        },
    },
    "Brighton": {
        "philosophy": "Technical possession football",
        "description": "Build-out play, possession circulation, ball progression",
        "strengths": [
            "Progressive ball carrying and passing",
            "Technical creativity from midfield",
            "Ball control and possession stability",
        ],
        "style_weights": {
            "possession": 0.22,
            "pressing": 0.12,
            "transitions": 0.10,
            "creativity": 0.18,
            "ball_progression": 0.22,
            "direct_play": 0.08,
            "defensive_work": 0.08,
        },
        "metric_preferences": {
            "goals_per_90": 0.10,
            "assists_per_90": 0.14,
            "progressive_carries": 0.22,
            "successful_dribbles": 0.14,
            "key_passes": 0.16,
            "xg": 0.10,
            "xa": 0.14,
        },
    },
    "Barcelona": {
        "philosophy": "Tiki-taka possession mastery",
        "description": "Intricate passing, ball control, wide playmaking",
        "strengths": [
            "Technical precision and short passing",
            "Creative midfield orchestration",
            "Possession-based control",
        ],
        "style_weights": {
            "possession": 0.28,
            "pressing": 0.08,
            "transitions": 0.08,
            "creativity": 0.22,
            "ball_progression": 0.18,
            "direct_play": 0.05,
            "defensive_work": 0.11,
        },
        "metric_preferences": {
            "goals_per_90": 0.11,
            "assists_per_90": 0.16,
            "progressive_carries": 0.16,
            "successful_dribbles": 0.16,
            "key_passes": 0.18,
            "xg": 0.11,
            "xa": 0.16,
        },
    },
    "Real Madrid": {
        "philosophy": "Counter-attacking sophistication",
        "description": "Efficient transitions, elite finishing, direct play",
        "strengths": [
            "Finishing efficiency and clinical edge",
            "Transition speed and execution",
            "Direct attacking penetration",
        ],
        "style_weights": {
            "possession": 0.15,
            "pressing": 0.10,
            "transitions": 0.25,
            "creativity": 0.15,
            "ball_progression": 0.12,
            "direct_play": 0.15,
            "defensive_work": 0.08,
        },
        "metric_preferences": {
            "goals_per_90": 0.18,
            "assists_per_90": 0.12,
            "progressive_carries": 0.12,
            "successful_dribbles": 0.12,
            "key_passes": 0.12,
            "xg": 0.18,
            "xa": 0.10,
        },
    },
    "Bayer Leverkusen": {
        "philosophy": "High-intensity attacking",
        "description": "Intense pressing, quick transitions, dynamic finishing",
        "strengths": [
            "Pressing intensity and recovery",
            "Transition speed and directness",
            "Box presence and finishing",
        ],
        "style_weights": {
            "possession": 0.10,
            "pressing": 0.26,
            "transitions": 0.24,
            "creativity": 0.12,
            "ball_progression": 0.10,
            "direct_play": 0.12,
            "defensive_work": 0.06,
        },
        "metric_preferences": {
            "goals_per_90": 0.17,
            "assists_per_90": 0.11,
            "progressive_carries": 0.11,
            "successful_dribbles": 0.13,
            "key_passes": 0.11,
            "xg": 0.17,
            "xa": 0.10,
        },
    },
    "Bayern Munich": {
        "philosophy": "Dominant control with intensity",
        "description": "Possession dominance, high pressing, tactical flexibility",
        "strengths": [
            "Possession control and pressing",
            "Technical quality and tactical intelligence",
            "All-phase ball dominance",
        ],
        "style_weights": {
            "possession": 0.24,
            "pressing": 0.22,
            "transitions": 0.12,
            "creativity": 0.18,
            "ball_progression": 0.14,
            "direct_play": 0.06,
            "defensive_work": 0.04,
        },
        "metric_preferences": {
            "goals_per_90": 0.13,
            "assists_per_90": 0.13,
            "progressive_carries": 0.16,
            "successful_dribbles": 0.12,
            "key_passes": 0.16,
            "xg": 0.13,
            "xa": 0.13,
        },
    },
    "Inter Milan": {
        "philosophy": "Organized counter-pressing",
        "description": "Structured defense, quick transitions, direct play",
        "strengths": [
            "Defensive organization and recovery",
            "Counter-attacking efficiency",
            "Direct penetration play",
        ],
        "style_weights": {
            "possession": 0.12,
            "pressing": 0.18,
            "transitions": 0.22,
            "creativity": 0.12,
            "ball_progression": 0.12,
            "direct_play": 0.14,
            "defensive_work": 0.10,
        },
        "metric_preferences": {
            "goals_per_90": 0.15,
            "assists_per_90": 0.10,
            "progressive_carries": 0.10,
            "successful_dribbles": 0.10,
            "key_passes": 0.10,
            "xg": 0.15,
            "xa": 0.10,
        },
    },
    "Paris Saint-Germain": {
        "philosophy": "Star-driven attacking football",
        "description": "Individual creativity, direct attacking, high defensive pressing",
        "strengths": [
            "Individual playmaking and creativity",
            "Direct attacking play",
            "Star-quality finishing",
        ],
        "style_weights": {
            "possession": 0.14,
            "pressing": 0.16,
            "transitions": 0.16,
            "creativity": 0.24,
            "ball_progression": 0.12,
            "direct_play": 0.12,
            "defensive_work": 0.06,
        },
        "metric_preferences": {
            "goals_per_90": 0.16,
            "assists_per_90": 0.14,
            "progressive_carries": 0.12,
            "successful_dribbles": 0.14,
            "key_passes": 0.16,
            "xg": 0.16,
            "xa": 0.12,
        },
    },
}


def get_club_profile(club_name: str) -> dict:
    """Get the tactical profile for a club."""
    return CLUB_PROFILES.get(club_name, {})


def list_clubs() -> list[str]:
    """Get all available clubs."""
    return list(CLUB_PROFILES.keys())
